# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Trieu Phan Ngoc
title: C++ Software Engineer
email: phantrieu580@gmail.com
website: https://github.com/TrieuPhanNgoc

#name: Trieu Phan Ngoc
# title: C++ Software Engineer
# email: phantrieu580@gmail.com
# website: https://github.com/TrieuPhanNgoc

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: TrieuPhanNgoc #facespics
github_username:  TrieuPhanNgoc
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: TrieuPhanNgoc
linkedin_username: TrieuPhanNgoc
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: Trieu PhanNgoc
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Trieu and I'm a junior embedded system programming. as well as experiencing of VBA for test tool programming from excel file (Auto Test) and UI design on TOPCON toolchain.
  
  I am most skilled in: <mark>C++</mark> and <mark>Java Script</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/TrieuPhanNgoc
        # link_text: Project Website
        additional_links:
          - title:  TrieuPhanNgoc/DataStructureAndAlgorithm
            icon: fab fa-github
            url: https://github.com/TrieuPhanNgoc/DataStructureAndAlgorithm
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Data Structure and Algorithm are the most important one that any programmer need to know
        description: | # this will include new lines to allow paragraphs
          I start learning Data Structure and Algorithm for using to solve problems which is needed to estimate the performance and memory management as well as

  #- title: Personal Project
    #layout: list
    content:
      - layout: top-middle
        title: IoT System
        link: github.com/TrieuPhanNgoc
        addition_links:
          - title: TrieuPhanNgoc/Embedded
            icon: fab fa-github
            url: https://github.com/TrieuPhanNgoc/Embedded
        
        quote: >
          Salangane House Monitoring System
        description:
          One of the projects which is built on the time of studying

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: FPT Software Company
        link: fpt-software.com
        # link_text: boringcompany.com
        sub_title: C++ Embedded Software Engineer
        caption: June 2021 - Present
        quote: >
          Automative System | Working with the CANbus system
        description: | # this will include new lines to allow paragraphs
          CANbus is a familiar term in this time - almost companies which works with automative system using this technology. FPT-Software no exception!

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Da Nang University of Science and Technology
        caption: 2017 - 2022
        sub_title: Electronic and Telecommunication Engineer
        quote: >
          Established in 2017, Science and Technology University is the oldest higher education institution in the Da Nang - Viet Nam.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Frisbee
      - Gaming
      - Reading
      - Anime / Cartoon
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme-gh-pahes/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
